version: '3.5'
services:
    # backend:
    #     image: backoffice-backend
    #     ports:
    #         - "80:80"
    database:
        image: mysql:5.7
        platform: linux/x86_64
        volumes:
            - "./.data/db:/var/lib/mysql"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mysql123456
            MYSQL_DATABASE: whatsapp
            MYSQL_USER: MainUser
            MYSQL_PASSWORD: MainPassword